<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="lenovo" failures="2" tests="2" name="Test(failed)" time="0.076" errors="0" timestamp="2022-11-28T12:50:23 IST">
  <testcase classname="TestNG.Class1" name="TC2" time="0.014">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at TestNG.Class1.TC2(Class1.java:18)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- TC2 -->
  <testcase classname="TestNG.Class2" name="TC5" time="0.001">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at TestNG.Class2.TC5(Class2.java:18)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- TC5 -->
  <testcase classname="TestNG.Class1" name="TC1" time="0.0">
    <ignored/>
  </testcase> <!-- TC1 -->
  <testcase classname="TestNG.Class1" name="TC3" time="0.0">
    <ignored/>
  </testcase> <!-- TC3 -->
  <testcase classname="TestNG.Class2" name="TC4" time="0.0">
    <ignored/>
  </testcase> <!-- TC4 -->
</testsuite> <!-- Test(failed) -->
